[2025-02-10T14:24:58.631+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T14:24:58.661+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.check_directory manual__2025-02-10T14:24:56.402860+00:00 [queued]>
[2025-02-10T14:24:58.674+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.check_directory manual__2025-02-10T14:24:56.402860+00:00 [queued]>
[2025-02-10T14:24:58.675+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T14:24:58.700+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): check_directory> on 2025-02-10 14:24:56.402860+00:00
[2025-02-10T14:24:58.711+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5544) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T14:24:58.714+0000] {standard_task_runner.py:72} INFO - Started process 5546 to run task
[2025-02-10T14:24:58.715+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'check_directory', 'manual__2025-02-10T14:24:56.402860+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmpcll3m3hz']
[2025-02-10T14:24:58.718+0000] {standard_task_runner.py:105} INFO - Job 237: Subtask check_directory
[2025-02-10T14:24:58.797+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.check_directory manual__2025-02-10T14:24:56.402860+00:00 [running]> on host b6443be51f35
[2025-02-10T14:24:58.904+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='check_directory' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T14:24:56.402860+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T14:24:56.402860+00:00'
[2025-02-10T14:24:58.906+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T14:24:58.907+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T14:24:58.908+0000] {logging_mixin.py:190} INFO - Current task name:check_directory state:running start_date:2025-02-10 14:24:58.662059+00:00
[2025-02-10T14:24:58.908+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-10T14:24:58.909+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T14:24:58.910+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-10T14:24:58.911+0000] {python.py:240} INFO - Done. Returned value was: check_file_in_directory
[2025-02-10T14:24:58.911+0000] {branch.py:38} INFO - Branch into check_file_in_directory
[2025-02-10T14:24:58.912+0000] {skipmixin.py:230} INFO - Following branch ('check_file_in_directory',)
[2025-02-10T14:24:59.190+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-10T14:24:59.225+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T14:24:59.226+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=check_directory, run_id=manual__2025-02-10T14:24:56.402860+00:00, execution_date=20250210T142456, start_date=20250210T142458, end_date=20250210T142459
[2025-02-10T14:24:59.239+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T14:24:59.240+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T14:24:59.240+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-10 14:24:56.427246+00:00
[2025-02-10T14:24:59.241+0000] {logging_mixin.py:190} INFO - Task hostname:b6443be51f35 operator:BranchPythonOperator
[2025-02-10T14:24:59.291+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T14:24:59.326+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T14:24:59.328+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
