[2025-02-10T14:49:50.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T14:49:50.529+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.check_directory manual__2025-02-10T14:49:48.733655+00:00 [queued]>
[2025-02-10T14:49:50.537+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.check_directory manual__2025-02-10T14:49:48.733655+00:00 [queued]>
[2025-02-10T14:49:50.538+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T14:49:50.555+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): check_directory> on 2025-02-10 14:49:48.733655+00:00
[2025-02-10T14:49:50.562+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5946) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T14:49:50.564+0000] {standard_task_runner.py:72} INFO - Started process 5948 to run task
[2025-02-10T14:49:50.566+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'check_directory', 'manual__2025-02-10T14:49:48.733655+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmphwi0ibub']
[2025-02-10T14:49:50.567+0000] {standard_task_runner.py:105} INFO - Job 257: Subtask check_directory
[2025-02-10T14:49:50.621+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.check_directory manual__2025-02-10T14:49:48.733655+00:00 [running]> on host b6443be51f35
[2025-02-10T14:49:50.878+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='check_directory' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T14:49:48.733655+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T14:49:48.733655+00:00'
[2025-02-10T14:49:50.879+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T14:49:50.879+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T14:49:50.879+0000] {logging_mixin.py:190} INFO - Current task name:check_directory state:running start_date:2025-02-10 14:49:50.530543+00:00
[2025-02-10T14:49:50.880+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-10T14:49:50.880+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T14:49:50.881+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-10T14:49:50.881+0000] {python.py:240} INFO - Done. Returned value was: check_file_in_directory
[2025-02-10T14:49:50.882+0000] {branch.py:38} INFO - Branch into check_file_in_directory
[2025-02-10T14:49:50.882+0000] {skipmixin.py:230} INFO - Following branch ('check_file_in_directory',)
[2025-02-10T14:49:50.891+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-10T14:49:50.921+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T14:49:50.923+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=check_directory, run_id=manual__2025-02-10T14:49:48.733655+00:00, execution_date=20250210T144948, start_date=20250210T144950, end_date=20250210T144950
[2025-02-10T14:49:50.935+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T14:49:50.936+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T14:49:50.936+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-10 14:49:48.749472+00:00
[2025-02-10T14:49:50.937+0000] {logging_mixin.py:190} INFO - Task hostname:b6443be51f35 operator:BranchPythonOperator
[2025-02-10T14:49:50.983+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T14:49:51.023+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T14:49:51.025+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
