[2025-02-06T07:39:38.781+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T07:39:38.928+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.check_file_in_directory manual__2025-02-06T07:39:33.593204+00:00 [queued]>
[2025-02-06T07:39:38.940+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.check_file_in_directory manual__2025-02-06T07:39:33.593204+00:00 [queued]>
[2025-02-06T07:39:38.941+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T07:39:38.957+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): check_file_in_directory> on 2025-02-06 07:39:33.593204+00:00
[2025-02-06T07:39:38.964+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T07:39:38.966+0000] {standard_task_runner.py:72} INFO - Started process 392 to run task
[2025-02-06T07:39:38.967+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'check_file_in_directory', 'manual__2025-02-06T07:39:33.593204+00:00', '--job-id', '579', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmpnhbok6_w']
[2025-02-06T07:39:38.968+0000] {standard_task_runner.py:105} INFO - Job 579: Subtask check_file_in_directory
[2025-02-06T07:39:39.027+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.check_file_in_directory manual__2025-02-06T07:39:33.593204+00:00 [running]> on host 003b7fbea265
[2025-02-06T07:39:39.104+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='check_file_in_directory' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T07:39:33.593204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T07:39:33.593204+00:00'
[2025-02-06T07:39:39.106+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T07:39:39.106+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T07:39:39.107+0000] {logging_mixin.py:190} INFO - Current task name:check_file_in_directory state:running start_date:2025-02-06 07:39:38.929139+00:00
[2025-02-06T07:39:39.108+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-06T07:39:39.109+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T07:39:39.110+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T07:39:39.115+0000] {python.py:240} INFO - Done. Returned value was: verify_file_reliability
[2025-02-06T07:39:39.116+0000] {branch.py:38} INFO - Branch into verify_file_reliability
[2025-02-06T07:39:39.117+0000] {skipmixin.py:230} INFO - Following branch ('verify_file_reliability',)
[2025-02-06T07:39:39.131+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-06T07:39:39.163+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T07:39:39.164+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=check_file_in_directory, run_id=manual__2025-02-06T07:39:33.593204+00:00, execution_date=20250206T073933, start_date=20250206T073938, end_date=20250206T073939
[2025-02-06T07:39:39.176+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T07:39:39.177+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T07:39:39.178+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-06 07:39:33.606625+00:00
[2025-02-06T07:39:39.178+0000] {logging_mixin.py:190} INFO - Task hostname:003b7fbea265 operator:BranchPythonOperator
[2025-02-06T07:39:39.224+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T07:39:39.266+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-06T07:39:39.268+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
