[2025-01-27T22:57:31.820+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T22:57:31.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task manual__2025-01-27T22:57:28.940946+00:00 [queued]>
[2025-01-27T22:57:31.847+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task manual__2025-01-27T22:57:28.940946+00:00 [queued]>
[2025-01-27T22:57:31.848+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-27T22:57:31.999+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): verifier_et_log_task> on 2025-01-27 22:57:28.940946+00:00
[2025-01-27T22:57:32.009+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-27T22:57:32.012+0000] {standard_task_runner.py:72} INFO - Started process 121 to run task
[2025-01-27T22:57:32.011+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'verifier_repertoire_dag', 'verifier_et_log_task', 'manual__2025-01-27T22:57:28.940946+00:00', '--job-id', '906', '--raw', '--subdir', 'DAGS_FOLDER/mydag_check_directory.py', '--cfg-path', '/tmp/tmp825ysesi']
[2025-01-27T22:57:32.013+0000] {standard_task_runner.py:105} INFO - Job 906: Subtask verifier_et_log_task
[2025-01-27T22:57:32.077+0000] {task_command.py:467} INFO - Running <TaskInstance: verifier_repertoire_dag.verifier_et_log_task manual__2025-01-27T22:57:28.940946+00:00 [running]> on host 340d747f4248
[2025-01-27T22:57:32.193+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='verifier_repertoire_dag' AIRFLOW_CTX_TASK_ID='verifier_et_log_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T22:57:28.940946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T22:57:28.940946+00:00'
[2025-01-27T22:57:32.195+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-27T22:57:32.195+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-27T22:57:32.196+0000] {logging_mixin.py:190} INFO - Current task name:verifier_et_log_task state:running start_date:2025-01-27 22:57:31.839352+00:00
[2025-01-27T22:57:32.197+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag and current dag run status:running
[2025-01-27T22:57:32.197+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T22:57:32.198+0000] {logging_mixin.py:190} INFO - [INFO] 2025-01-27 22:57:32.198539 - Vérification du répertoire : C:/Users/HP/Documents/TextimportationPython
[2025-01-27T22:57:32.199+0000] {logging_mixin.py:190} INFO - jhjhjhjh [ERREUR] 2025-01-27 22:57:32.199069 - Le répertoire 'C:/Users/HP/Documents/TextimportationPython' n'existe pas.
[2025-01-27T22:57:32.199+0000] {python.py:240} INFO - Done. Returned value was: False
[2025-01-27T22:57:32.230+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T22:57:32.231+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=verifier_repertoire_dag, task_id=verifier_et_log_task, run_id=manual__2025-01-27T22:57:28.940946+00:00, execution_date=20250127T225728, start_date=20250127T225731, end_date=20250127T225732
[2025-01-27T22:57:32.244+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-27T22:57:32.244+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-27T22:57:32.245+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag queued_at:2025-01-27 22:57:28.951359+00:00
[2025-01-27T22:57:32.246+0000] {logging_mixin.py:190} INFO - Task hostname:340d747f4248 operator:PythonOperator
[2025-01-27T22:57:32.268+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-27T22:57:32.290+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T22:57:32.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
