[2025-02-09T22:47:59.641+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T22:47:59.696+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-09T22:47:42.478773+00:00 [queued]>
[2025-02-09T22:47:59.943+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-09T22:47:42.478773+00:00 [queued]>
[2025-02-09T22:47:59.945+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-09T22:47:59.971+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): verify_file_reliability> on 2025-02-09 22:47:42.478773+00:00
[2025-02-09T22:47:59.984+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4372) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-09T22:47:59.987+0000] {standard_task_runner.py:72} INFO - Started process 4374 to run task
[2025-02-09T22:47:59.989+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'verify_file_reliability', 'manual__2025-02-09T22:47:42.478773+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmpjtjeqult']
[2025-02-09T22:47:59.991+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask verify_file_reliability
[2025-02-09T22:48:00.138+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-09T22:47:42.478773+00:00 [running]> on host b6443be51f35
[2025-02-09T22:48:00.574+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='verify_file_reliability' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T22:47:42.478773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T22:47:42.478773+00:00'
[2025-02-09T22:48:00.581+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-09T22:48:00.591+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-09T22:48:00.609+0000] {logging_mixin.py:190} INFO - Current task name:verify_file_reliability state:running start_date:2025-02-09 22:47:59.697373+00:00
[2025-02-09T22:48:00.614+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-09T22:48:00.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T22:48:00.618+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-09T22:48:00.653+0000] {logging_mixin.py:190} INFO - camarche22 /opt/***/files/in ['.csv'] ['utf-8', 'ISO-8859-1', 'Windows-1252']
[2025-02-09T22:48:00.768+0000] {logging_mixin.py:190} INFO - 
üìÇ Contenu du fichier (utf-8): √âcritures comptables article.csv
[2025-02-09T22:48:00.814+0000] {logging_mixin.py:190} INFO -   Date comptabilisation      N¬∞ lot Type √©criture N¬∞ document  N¬∞ s√©quence
0            16/12/2024         NaN         Vente   BL1900145        15735
1            16/12/2024         NaN         Vente      107012        15734
2            11/01/2025  16LABCDE24    Production   RPO000460        15733
3            11/01/2025  16LABCDE24    Production   RPO000460        15732
4            11/01/2025  16LABCDE24    Production   RPO000460        15731
[2025-02-09T22:48:04.493+0000] {logging_mixin.py:190} INFO - ‚úÖLignes  ('‚úÖ Le fichier respecte les colonnes attendues et les types de donn√©es.', True) 10923
[2025-02-09T22:48:04.500+0000] {logging_mixin.py:190} INFO - merci
[2025-02-09T22:48:04.524+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2025-02-09T22:48:04.568+0000] {logging_mixin.py:190} INFO - (('attendancedb',), ('caprostockdb',), ('information_schema',), ('mysql',), ('netvision_db',), ('performance_schema',), ('pointing_db',), ('posgpt_db',), ('pythondb',), ('sys',), ('testimportdb',))
[2025-02-09T22:48:04.690+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Donn√©es supprim√©es avant insertion.
[2025-02-09T22:48:06.587+0000] {sql.py:691} INFO - Loaded 1000 rows into temp_ecc so far
[2025-02-09T22:48:08.067+0000] {sql.py:691} INFO - Loaded 2000 rows into temp_ecc so far
[2025-02-09T22:48:09.353+0000] {sql.py:691} INFO - Loaded 3000 rows into temp_ecc so far
[2025-02-09T22:48:10.814+0000] {sql.py:691} INFO - Loaded 4000 rows into temp_ecc so far
[2025-02-09T22:48:12.624+0000] {sql.py:691} INFO - Loaded 5000 rows into temp_ecc so far
[2025-02-09T22:48:13.697+0000] {sql.py:691} INFO - Loaded 6000 rows into temp_ecc so far
[2025-02-09T22:48:14.666+0000] {sql.py:691} INFO - Loaded 7000 rows into temp_ecc so far
[2025-02-09T22:48:15.855+0000] {sql.py:691} INFO - Loaded 8000 rows into temp_ecc so far
[2025-02-09T22:48:17.015+0000] {sql.py:691} INFO - Loaded 9000 rows into temp_ecc so far
[2025-02-09T22:48:18.045+0000] {sql.py:691} INFO - Loaded 10000 rows into temp_ecc so far
[2025-02-09T22:48:19.015+0000] {sql.py:694} INFO - Done loading. Loaded a total of 10923 rows into temp_ecc
[2025-02-09T22:48:19.019+0000] {logging_mixin.py:190} INFO - connexion sql reussie True
[2025-02-09T22:48:19.073+0000] {logging_mixin.py:190} INFO - ‚ùå Erreur lors du d√©placement du fichier : [Errno 13] Permission denied: '/opt/***/files/in/√âcritures comptables article.csv'
[2025-02-09T22:48:19.079+0000] {python.py:240} INFO - Done. Returned value was: import_temp_ecc_to_ecc
[2025-02-09T22:48:19.080+0000] {branch.py:38} INFO - Branch into import_temp_ecc_to_ecc
[2025-02-09T22:48:19.081+0000] {skipmixin.py:230} INFO - Following branch ('import_temp_ecc_to_ecc',)
[2025-02-09T22:48:19.115+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-09T22:48:19.188+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T22:48:19.189+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=verify_file_reliability, run_id=manual__2025-02-09T22:47:42.478773+00:00, execution_date=20250209T224742, start_date=20250209T224759, end_date=20250209T224819
[2025-02-09T22:48:19.207+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-09T22:48:19.209+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-09T22:48:19.210+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-09 22:47:42.515678+00:00
[2025-02-09T22:48:19.211+0000] {logging_mixin.py:190} INFO - Task hostname:b6443be51f35 operator:BranchPythonOperator
[2025-02-09T22:48:19.250+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T22:48:19.299+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-09T22:48:19.302+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
