[2025-02-10T14:53:24.457+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T14:53:24.478+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-10T14:53:18.087043+00:00 [queued]>
[2025-02-10T14:53:24.487+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-10T14:53:18.087043+00:00 [queued]>
[2025-02-10T14:53:24.487+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T14:53:24.502+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): verify_file_reliability> on 2025-02-10 14:53:18.087043+00:00
[2025-02-10T14:53:24.510+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6019) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T14:53:24.512+0000] {standard_task_runner.py:72} INFO - Started process 6021 to run task
[2025-02-10T14:53:24.512+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'verify_file_reliability', 'manual__2025-02-10T14:53:18.087043+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmpfn8k2vcw']
[2025-02-10T14:53:24.513+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask verify_file_reliability
[2025-02-10T14:53:24.553+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-10T14:53:18.087043+00:00 [running]> on host b6443be51f35
[2025-02-10T14:53:24.832+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='verify_file_reliability' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T14:53:18.087043+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T14:53:18.087043+00:00'
[2025-02-10T14:53:24.833+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T14:53:24.834+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T14:53:24.834+0000] {logging_mixin.py:190} INFO - Current task name:verify_file_reliability state:running start_date:2025-02-10 14:53:24.479213+00:00
[2025-02-10T14:53:24.835+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-10T14:53:24.835+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T14:53:24.836+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-10T14:53:24.837+0000] {logging_mixin.py:190} INFO - camarche22 /opt/***/files/in ['.csv'] ['utf-8', 'ISO-8859-1', 'Windows-1252']
[2025-02-10T14:53:24.845+0000] {logging_mixin.py:190} INFO - 
üìÇ Contenu du fichier (utf-8): √âcritures comptables article - Copie.csv
[2025-02-10T14:53:24.855+0000] {logging_mixin.py:190} INFO -   Date comptabilisation      N¬∞ lot Type √©criture N¬∞ document  N¬∞ s√©quence
0            11/01/2025  16LABCDE24    Production   RPO000460        15733
1            11/01/2025  16LABCDE24    Production   RPO000460        15731
[2025-02-10T14:53:24.860+0000] {logging_mixin.py:190} INFO - ‚úÖLignes  ('‚úÖ Le fichier respecte les colonnes attendues et les types de donn√©es.', True) 2
[2025-02-10T14:53:24.864+0000] {logging_mixin.py:190} INFO - merci
[2025-02-10T14:53:24.872+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2025-02-10T14:53:24.884+0000] {logging_mixin.py:190} INFO - (('attendancedb',), ('caprostockdb',), ('information_schema',), ('mysql',), ('netvision_db',), ('performance_schema',), ('pointing_db',), ('posgpt_db',), ('pythondb',), ('sys',), ('testimportdb',))
[2025-02-10T14:53:24.889+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Donn√©es supprim√©es avant insertion.
[2025-02-10T14:53:24.900+0000] {sql.py:694} INFO - Done loading. Loaded a total of 2 rows into temp_ecc
[2025-02-10T14:53:24.901+0000] {logging_mixin.py:190} INFO - connexion sql reussie True
[2025-02-10T14:53:24.916+0000] {logging_mixin.py:190} INFO - ‚ùå Erreur lors du d√©placement du fichier : [Errno 13] Permission denied: '/opt/***/files/in/√âcritures comptables article - Copie.csv'
[2025-02-10T14:53:24.918+0000] {python.py:240} INFO - Done. Returned value was: import_temp_ecc_to_ecc
[2025-02-10T14:53:24.919+0000] {branch.py:38} INFO - Branch into import_temp_ecc_to_ecc
[2025-02-10T14:53:24.919+0000] {skipmixin.py:230} INFO - Following branch ('import_temp_ecc_to_ecc',)
[2025-02-10T14:53:24.931+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-10T14:53:24.953+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T14:53:24.954+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=verify_file_reliability, run_id=manual__2025-02-10T14:53:18.087043+00:00, execution_date=20250210T145318, start_date=20250210T145324, end_date=20250210T145324
[2025-02-10T14:53:24.963+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-10T14:53:24.964+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-10T14:53:24.964+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-10 14:53:18.097462+00:00
[2025-02-10T14:53:24.965+0000] {logging_mixin.py:190} INFO - Task hostname:b6443be51f35 operator:BranchPythonOperator
[2025-02-10T14:53:25.008+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T14:53:25.040+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-10T14:53:25.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
